### ISSUE TITLE
210E h planck costant doesn't fit in 1D455 mathematical italic small h

### ISSUE THREAD

**Issue by antonio-guermani** [notofonts/math#1]
Sorry I'm a newbie.
In the Unicode standard **Mathematical Alphanumeric Symbols**, italic small letter "h" 1D455 is not present but reserved because refers to 210E h planck constant.
The problem is that both in **Noto Sans** and in **Noto Serif**, the fonts in 210E are italic but are completely different in shape so those "h" don't fit the other letters from 1D450 to 1D45F.
The result is that is impossible to type mathematical formulas with italic small letter containing an "h"

**Comment by simoncozens** [comment]
This is now fixed, after #33.
