### ISSUE TITLE
OpenType layout features missing

### ISSUE THREAD

**Issue by jungshik** [notofonts/math#15]
Moved from googlei18n/noto-alpha#199 (originally reported by @roozbehp ):

Certain characters in the symbol font are combining characters for other symbols. For example, the characters in the range U+20D0 to U+20F0 are supposed to be combined with other symbols.

Some of these are expected to combine with letter-like characters at U+21xx or U+1D4xx to U+1D7xx ranges. Some of the characters in those ranges are even soft-dotted: when combined with a combing accent-like character, they should lose their dots. For example, the combination <U+1D456,U+20D7> (italic small i, combining right arrow above) should render without a dot. (Screenshot attached.)

For these, the Noto Symbols font needs GPOS and GSUB tables, but there are no such tables in the font.

![noto 4](https://cloud.githubusercontent.com/assets/8578343/8810164/f52e46f6-2fa1-11e5-9fe8-0848d367683a.png)

**Comment by simoncozens** [comment]
Mark attachment is (largely) happening now, but there are some missing base anchors which are tracked in #5. The soft-dotted issue is still present and tracked in #12.
