### ISSUE TITLE
Stylistically inconsistent mathematical alphanumerics

### ISSUE THREAD

**Issue by dscorbett** [notofonts/math#2]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
Mathematical alphanumeric symbols in the BMP don’t stylistically match those in the SMP.

The Mathematical Alphanumeric Symbols block includes bold Latin letters, sans-serif Latin letters, and sans-serif bold Latin letters. The implication is that the Latin letters that are not explicitly sans-serif are serifed. This goes for the ASCII letters and digits too. [Table 2.1 of UTR notofonts/latin-greek-cyrillic#239](https://www.unicode.org/reports/tr25/tr25-15.pdf#page=7) makes this explicit. Therefore, the ASCII letters and digits should have serifs, and should not duplicate the sans-serif range in the SMP.

The BMP Greek letters have no SMP sans-serif counterparts to be confused with, but I think that as long as the bold/italic Greek letters have such a distinctive style, the plain Greek letters should too.

The BMP fraktur letters are not in the same style as the SMP fraktur letters. You can tell by comparing the fraktur letters to the bold fraktur letters.

### Character data
A𝖠𝐀
U+0041 LATIN CAPITAL LETTER A
U+1D5A0 MATHEMATICAL SANS-SERIF CAPITAL A
U+1D400 MATHEMATICAL BOLD CAPITAL A
Α𝚨
U+0391 GREEK CAPITAL LETTER ALPHA
U+1D6A8 MATHEMATICAL BOLD CAPITAL ALPHA
ℑ𝕴𝔍𝕵
U+2111 BLACK-LETTER CAPITAL I
U+1D574 MATHEMATICAL BOLD FRAKTUR CAPITAL I
U+1D50D MATHEMATICAL FRAKTUR CAPITAL J
U+1D575 MATHEMATICAL BOLD FRAKTUR CAPITAL J

### Screenshot
![A𝖠𝐀 Α𝚨 ℑ𝕴𝔍𝕵](https://user-images.githubusercontent.com/1124347/52353358-64bb3a80-29fc-11e9-81c0-784facb16270.png)

**Comment by simoncozens** [comment]
These are now more consistent after #33.
