### ISSUE TITLE
Built fonts aren't showing up on notofonts.github.io

### ISSUE THREAD

**Issue by iwsfutcmd** [notofonts/math#30]
"Latest fonts" section [here](https://notofonts.github.io/#math) is blank. Nothing in the notofonts.github.io repository either.

Noto Sans Math is being distributed by Google Fonts, so I assume this is an oversight rather than not yet having a released version.

**Comment by simoncozens** [comment]
This should now be corrected (next time the script runs, tomorrow) bu the latest release.
