### ISSUE TITLE
No unhinted/otf fonts generated for Noto Sans Math

### ISSUE THREAD

**Issue by yrogge** [notofonts/math#32]
Everything is in the tittle!
The directories structure of Noto Sans Math does not respect the (new) Noto standard.
It is the only script of all ones without such OTF version.

**Comment by simoncozens** [comment]
I am awaiting a delivery of new Noto Sans Math sources, so I haven't put much work into getting the old version working. I hope that we will be able to resolve this soon when the new version arrives.

**Comment by yrogge** [comment]
OK. Thanks.

**Comment by joergklein** [comment]
I am a LaTeX user. It would be great if the Noto font family, in particular the mathematics font could get an update before the 10th of February, for the new TeX Live 2023 release.

Plan for TeX Live 2023:
10feb: candidate/final sources committed, test builds begin.
17feb: tlpretest begins, CTAN updates continue there and on tlnet.
3 March: code freeze for final release, major bug fixes only.
10 March: last updates of CTAN, last corrections to documentation.
12 March: handover of TL image for packaging/testing of TeX collection.
19 March: public release (also of MacTeX).
May: Delivery of the TeX Collection DVD to members.

**Comment by simoncozens** [comment]
This should now be corrected (next time the script runs, tomorrow) by the latest release. Sorry we missed the TeXLive deadline. :-/
