### ISSUE TITLE
Scrapped 2AAC and 2BFE

### ISSUE THREAD

**Issue by Mercury13** [notofonts/math#34]
### Title 
  2AAC and 2BFE are missing now

### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
This repo, release channel
2023-03-15

### Font Version
2.539

### OS name and version
All OS

### Application name and version
All apps

### Issue
Characters 2AAC and 2BFE have gone 2.002 → 2.539

### Character data
U+2AAC smaller than or equal to (symmetrical 2AAD is here!)
U+2BFE reversed right angle

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/225431007-fbfdab27-5dfa-48c2-83f7-0c53ede2ac9c.png)

**Comment by simoncozens** [comment]
This was my fault. I'll fix it.
