### ISSUE TITLE
1D6CD advance width is 0 [easy]

### ISSUE THREAD

**Issue by Mercury13** [notofonts/math#35]
### Title 
1D6CD’s advance width is 0, and TopAccent marker is somewhere else

### Font 
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: this repo, release channel
Date: 2023-03-15

### Font Version
2.539

### OS name and version
All OS

### Application name and version
All apps

### Issue
1D6CD’s advance width is 0, and TopAccent marker is not in the centre.

### Character data
U+1D6CD mathematical bold small Mu

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/225444620-e4a7ac70-7962-423b-a428-ca900eae1f91.png)

**Comment by Mercury13** [comment]
Still 0.

**Comment by simoncozens** [comment]
Yes; that is why the issue is still open. If I had fixed the bug, I would have closed the issue. :-)
