### ISSUE TITLE
U+2273 and U+2A9D variants have reversed tildes

### ISSUE THREAD

**Issue by dscorbett** [notofonts/math#38]
### Font
NotoSansMath-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/math/releases/tag/NotoSansMath-v2.539
Date: 2023-03-18

### Font version
Version 2.539

### Issue
When followed by VS1, the tildes of U+2273 and U+2A9D are reversed from how they should look.

### Character data
≳︀⪝︀
U+2273 GREATER-THAN OR EQUIVALENT TO
U+FE00 VARIATION SELECTOR-1
U+2A9D SIMILAR OR LESS-THAN
U+FE00 VARIATION SELECTOR-1

### Screenshots
![≳︀⪝︀](https://user-images.githubusercontent.com/1124347/226215578-c421aae8-1122-4134-a815-61c75f5523c7.png)
Compare the default glyphs:
![≳⪝](https://user-images.githubusercontent.com/1124347/226215816-8506b886-8291-423b-a0ef-612e17ea2e1b.png)

**Comment by simoncozens** [comment]
I see *why* this is the case. The UVS for 2273 FE00, and arguably this design does have the tilde follow the slant of the lower leg... Although I suspect what is intended by Unicode is something more like (excuse the bad drawing):

<img width="261" alt="Screenshot 2023-04-28 at 09 01 13" src="https://user-images.githubusercontent.com/106728/235090345-a000d335-c2bf-4f1e-bcfb-bf0340cd4050.png">

Let's compare some other math fonts.
