### ISSUE TITLE
Inconsistent glyphs for horizontal brackets

### ISSUE THREAD

**Issue by dscorbett** [notofonts/math#4]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
The glyphs of U+23B4 TOP SQUARE BRACKET and U+23B5 BOTTOM SQUARE BRACKET are inconsistent in size and position with those of the other top and bottom delimiters. I am pretty sure U+23B6 BOTTOM SQUARE BRACKET OVER TOP SQUARE BRACKET is just for terminal emulation, not for math, but as long as this font supports it, it should be consistent with those delimiters too.

### Character data
⎴⎵⎶⏜⏝
U+23B4 TOP SQUARE BRACKET
U+23B5 BOTTOM SQUARE BRACKET
U+23B6 BOTTOM SQUARE BRACKET OVER TOP SQUARE BRACKET
U+23DC TOP PARENTHESIS
U+23DD BOTTOM PARENTHESIS

### Screenshot
![⎴⎵⎶⏜⏝](https://user-images.githubusercontent.com/1124347/52579668-9ebd7f80-2df4-11e9-8a77-d34c1b17fa77.png)

**Comment by simoncozens** [comment]
This is *not* fixed by #33.
