### ISSUE TITLE
<U+2216, U+FE00> should look the same as U+2216

### ISSUE THREAD

**Issue by dscorbett** [notofonts/math#40]
### Font
NotoSansMath-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/math/releases/tag/NotoSansMath-v2.539
Date: 2023-03-18

### Font version
Version 2.539

### Issue
<U+2216, U+FE00> looks different from U+2216, but that sequence is not a standardized variation sequence. U+FE00 should have no effect in that context.

### Character data
∖︀∖
U+2216 SET MINUS
U+FE00 VARIATION SELECTOR-1
U+2216 SET MINUS

### Screenshot
![∖︀∖](https://user-images.githubusercontent.com/1124347/226222024-900c00a5-cbfd-4a19-9125-182666c41a4d.png)

**Comment by simoncozens** [comment]
I don't know where this UVS idea came from but it obviously came from *somewhere*, so I've disabled it for now (and removed the glyphs from exporting to the final TTF) rather than deleting it from the font sources. The `ccmp` substitutions contained this:

```
sub setminus VS1 by setminus.uv001;
sub setminus VS1 by setminus.uv001.ssty1;
sub setminus VS1 by setminus.uv001.ssty2;
```

which is clearly wrong.
