### ISSUE TITLE
Missing anchor points in Noto Sans Math

### ISSUE THREAD

**Issue by dscorbett** [notofonts/math#5]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
Mark attachment is underdeveloped in this font. The only base anchors are on plain Greek and Latin letters and sans-serif Latin letters, and the only mark anchors are on characters in Combining Diacritical Marks. All of the digits and Greek and Latin letters should have base anchors, and maybe the Hebrew ones too. All of the characters categorized in Unicode as marks should have mark anchors. U+20D2 COMBINING LONG VERTICAL LINE OVERLAY, U+20D3 COMBINING SHORT VERTICAL LINE OVERLAY, and U+0338 COMBINING LONG SOLIDUS OVERLAY (if it gets added to the font) should be able to combine with operators too. U+20E7 COMBINING ANNUITY SYMBOL should have positive advance width so it doesn’t overlap the next glyph.

### Character data
𝑛⃧ϑ⃐ϖ⃑𝐴⃫⊰⃒
U+1D45B MATHEMATICAL ITALIC SMALL N
U+20E7 COMBINING ANNUITY SYMBOL
U+03D1 GREEK THETA SYMBOL
U+20D0 COMBINING LEFT HARPOON ABOVE
U+03D6 GREEK PI SYMBOL
U+20D1 COMBINING RIGHT HARPOON ABOVE
U+1D434 MATHEMATICAL ITALIC CAPITAL A
U+20EB COMBINING LONG DOUBLE SOLIDUS OVERLAY
U+22B0 PRECEDES UNDER RELATION
U+20D2 COMBINING LONG VERTICAL LINE OVERLAY

### Screenshot
![𝑛⃧ϑ⃐ϖ⃑𝐴⃫⊰⃒](https://user-images.githubusercontent.com/1124347/52662232-c2a2c300-2ed1-11e9-9048-777f3cf02b84.png)

**Comment by simoncozens** [comment]
This is still not fixed, despite the #33 update; I added centre anchors, but there are no top or bottom anchors.

**Comment by khaledhosny** [comment]
This depends on how this font is intended to be used. For math layout, using a dedicated math layout engine, then GPOS anchor positioning is ignored and the MATH table positioning is used which works differently. For other uses, I think other Noto fonts should be preferable.

**Comment by simoncozens** [comment]
Agree with Khaled. Math anchors are the way forward here; expecting to be able to typeset math without a math typesetting engine is a recipe for disappointment, no matter what we do in the GPOS table.

**Comment by dscorbett** [comment]
Does my original report’s sample string look correct in this font using the MATH table? I tested it in HTML with MathML and it still looked mostly wrong.

**Comment by khaledhosny** [comment]
It looks fine in Firefox (except the overlay accents, does not look like MathML has such a concept):
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/3b65758a-ad79-4c82-8eb4-feec2795733e">

Chrome is worse as it does not seem to use the top accent positioning data from MATH table:
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/8ea925b2-d09b-4492-adc8-76b7b7429301">

I don’t even know what is going on with Safari (it seems to use a different font for the accents):
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/af12d807-91a2-4f18-b094-0f3dcaf57ad7">

But it is the same for any other math font, and adding GPOS accents is not going to change the situation with MathML.

```html
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
    <style>
        math {
            font-family: 'Cambria Math';
            font-size: 12pt;
        }
    </style>
</head>
<body>
    <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mover accent="true">
            <mi>&#x1D45B;</mi>
            <mo stretchy="false">&#x20E7;</mo>
        </mover>
        <mspace width="1em"></mspace>
        <mover accent="true">
            <mi>&#x03D1;</mi>
            <mo stretchy="false">&#x20D0;</mo>
        </mover>
        <mspace width="1em"></mspace>
        <mover accent="true">
            <mi>&#x03D6;</mi>
            <mo stretchy="false">&#x20D1;</mo>
        </mover>
        <mspace width="1em"></mspace>
        <mover accent="true">
            <mi>&#x1D434;</mi>
            <mo stretchy="false">&#x20EB;</mo>
        </mover>
        <mspace width="1em"></mspace>
        <mover accent="true">
            <mi>&#x22B0;</mi>
            <mo stretchy="false">&#x20D2;</mo>
        </mover>
    </math>
</body>
</html>
```

TeX engines, do better. XeTeX/LuaTeX:
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/66ad9224-2f8e-4a91-a879-8fc263eef9db">

```tex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Noto Sans Math}
\begin{document}
\[
    \Umathaccent fixed 7\symoperators "20E7 {^^^^^^01d45b}\quad%
    \Umathaccent fixed 7\symoperators "20D0 {^^^^03d1}\quad%
    \Umathaccent fixed 7\symoperators "20D1 {^^^^03d6}\quad%
    \Umathaccent fixed 7\symoperators "20EB {^^^^^^01d434}\quad%
    \Umathaccent fixed 7\symoperators "20D2 {^^^^22b0}\quad%
\]
\end{document}
```

LuaTeX even has explicit support for overlay accents:
<img width="134" alt="image" src="https://github.com/notofonts/math/assets/93914/5b3e5c92-f9c0-459b-bfb4-9e8b474f7133">
```tex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Noto Sans Math}
\begin{document}
\[
    \Umathaccent fixed 7\symoperators "20E7 {^^^^^^01d45b}\quad%
    \Umathaccent fixed 7\symoperators "20D0 {^^^^03d1}\quad%
    \Umathaccent fixed 7\symoperators "20D1 {^^^^03d6}\quad%
    \Umathaccent overlay 7\symoperators "20EB {^^^^^^01d434}\quad%
    \Umathaccent overlay 7\symoperators "20D2 {^^^^22b0}\quad%
\]
\end{document}
```
