### ISSUE TITLE
Integrals are too upright and confusable with brackets/lines

### ISSUE THREAD

**Issue by simoncozens** [notofonts/math#51]
```
\documentclass{article}
\pagestyle{empty}
\usepackage{unicode-math}
\begin{document}

\setmathfont{NotoSansMath-Regular.otf}

$$\int _{0}^{2}\left( \frac{-27}{2}+y\right) dy=\left (\frac{-27}{2}y+\frac{y^{2}}{2}\right )\Big |_{0}^{2} = -25
$$

\end{document}
```

<img width="398" alt="Screenshot 2024-01-12 at 09 21 45" src="https://github.com/notofonts/math/assets/106728/8a2d4da5-f676-49fc-b394-31d51b49aa8d">

**Comment by apoorvpotnis** [comment]
A slightly slanting symbol with wider hooks would perhaps look better, in my opinion, similar to Fira Sans Math: https://github.com/firamath/firamath

**Comment by khaledhosny** [comment]
New design (#63):
<img width="613" alt="image" src="https://github.com/notofonts/math/assets/93914/f6f873b9-1e18-4bd0-a3c9-2923e84ca8d6">
