### ISSUE TITLE
Minusplus symbol misaligned

### ISSUE THREAD

**Issue by simoncozens** [notofonts/math#53]
When placed together with plusminus it looks reasonable:

<img width="136" alt="Screenshot 2024-01-12 at 09 27 33" src="https://github.com/notofonts/math/assets/106728/996e8ee8-fa29-4092-bc29-a181c7fac179">

But in the context of an equation it really doesn't work:

<img width="320" alt="Screenshot 2024-01-12 at 09 27 58" src="https://github.com/notofonts/math/assets/106728/6ce44434-798d-43ca-86b4-10e1e68a6aa7">

**Comment by khaledhosny** [comment]
The design of both symbols need to be adjusted so that they have the same bounding box as the plus while keeping the middle bar aligned with that of the plus (they are too small to for use in math equations, as well as many other operators).

**Comment by khaledhosny** [comment]
#63:
<img width="369" alt="image" src="https://github.com/notofonts/math/assets/93914/a12cec08-34e8-448a-9b78-862b0e977ae1">
