### ISSUE TITLE
Request to consider splitting Noto Sans Math into two fonts---a serif and a sans serif one

### ISSUE THREAD

**Issue by apoorvpotnis** [notofonts/math#54]
This is a request to consider splitting the Noto Sans Math font into two fonts---a serif and a sans serif one. 

The current `NotoSansMath-Regular.otf` font contains some alphanumeric symbols, such as mathematical Greek letters (italic, upright, bold and normal), script, calligraphic and Fraktur letters, whilst other symbols such some Latin letters, and all the non-alphanumeric symbols, such as brackets, integrals, etc. in sans serif. A sans serif font should contain all the sans serif matching glyphs and a serif font should contain all serif glyphs (except the sans serif block). Other sans serif math fonts, such as Fira have all sans serif glyphs (except perhaps script and Fraktur, for which which new glyphs would need to be created.) 

Since there are really few sans serif fonts with math support, a proper Noto Sans Math font would prove to be immensely useful, say for creating Beamer presentations, on websites where people prefer sans serif fonts (using mathml) or for figures/section headers in books. 

When one wishes to insert U+1D400 MATHEMATICAL BOLD CAPITAL A using Noto Sans Math, he/she should get a sans serif bold capital A, not a serif one, as is the case currently with Noto Sans Math. This is true irrespective of the software used, LaTeX, Word, MathML or anything else.

The font, as it stands, it a mishmash of randomly appearing serif and sans serif letters which in my honest/humble opinion looks ugly. I earnestly apologize as this may come as rude or annoying, but the truth is that the font is not really acceptable for use in the present state. I don't wish to undermine the efforts of the font creators, but the serifs need to go. A new Noto Serif Math font can be created from those, but the other non-alphanumeric symbols would need to be created for that. Sorry for writing such a long message.

**Comment by berrymot** [comment]
agree tbh, it's a weird mix as-is

**Comment by dflipo** [comment]
I agree completely. The good news is that (nearly) all Sans glyphs are *already* in the font.  Missing are Greek Italic Sans but they are easily created slanting Greek Sans (range U+0391 - U+03F5) by 11°.   Some more fixes should be applied to imath, jmath, PlanckConstant, … not a big deal imho.

**Comment by apoorvpotnis** [comment]
@dflipo Assuming that the math glyphs are not different from the text glyphs, italic sans Greek glyphs are already present in the text Noto Sans fonts. So the work has been further reduced.

**Comment by Mercury13** [comment]
I agree, and maybe even drop Sans. Most of maths is serif.

**Comment by apoorvpotnis** [comment]
Regarding most of math being serif, I think it's mostly a chicken and egg
problem. No one uses sans serif math, because no (or very few) sans serif
fonts exist in the first place!

**Comment by khaledhosny** [comment]
Noto Sans Math is a purely sans font after #57 . I don’t think there are plans for a Noto Serif Math, though I agree it would be a useful addition.

**Comment by apoorvpotnis** [comment]
> Noto Sans Math is a purely sans font after #57 . I don’t think there are plans for a Noto Serif Math, though I agree it would be a useful addition.

If one were to request a Noto Serif Math font, where would be a suitable place to request? Is it okay to create a feature request / issue in this repository?

**Comment by khaledhosny** [comment]
I think this issue is as good as it gets.
