### ISSUE TITLE
Indistinct 𝑛-ary operators

### ISSUE THREAD

**Issue by dscorbett** [notofonts/math#6]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
The <var>n</var>-ary operators U+2A01, U+2A02, U+2A00, and U+2AFC look the same as their binary counterparts U+2295, U+2297, U+2299, and U+2AF4.

### Character data
⊕⨁
U+2295 CIRCLED PLUS
U+2A01 N-ARY CIRCLED PLUS OPERATOR
⊗⨂
U+2297 CIRCLED TIMES
U+2A02 N-ARY CIRCLED TIMES OPERATOR
⊙⨀
U+2299 CIRCLED DOT OPERATOR
U+2A00 N-ARY CIRCLED DOT OPERATOR
⫴⫼
U+2AF4 TRIPLE VERTICAL BAR BINARY RELATION
U+2AFC LARGE TRIPLE VERTICAL BAR OPERATOR

### Screenshot
![⊕⨁ ⊗⨂ ⊙⨀ ⫴⫼](https://user-images.githubusercontent.com/1124347/52731319-72883700-2f8b-11e9-8650-2a15f88d41d0.png)

**Comment by simoncozens** [comment]
This is fixed with #33.
