### ISSUE TITLE
Arabic math alpahabet needs redesign

### ISSUE THREAD

**Issue by khaledhosny** [notofonts/math#64]
The current glyphs are based on Noto Naskh Arabic, which is a modulated design and does not fit the rest of Noto Sans Math.

**Comment by berrymot** [comment]
maybe cf #54

**Comment by khaledhosny** [comment]
Noto Sans Math is already a purely-sans typeface (except script and fraktur alphabets, #61), so this is to make the Arabic glyphs follow suite. Whether Noto projects wants to pursue a Noto Serif Math project or not is orthogonal to this.

**Comment by khaledhosny** [comment]
Current:
<img width="654" alt="image" src="https://github.com/notofonts/math/assets/93914/d7dc57e1-5b87-41d6-8556-911ad682d8ea">


#63:
<img width="654" alt="image" src="https://github.com/notofonts/math/assets/93914/9877ae91-13d5-4d6d-b4ee-ffeb2e67426c">
