### ISSUE TITLE
Weight of ∞ (U+221E) seems too low

### ISSUE THREAD

**Issue by Enivex** [notofonts/math#68]
### Font 
NotoSansMath-Regular.ttf

### Where the font came from, and when
https://github.com/notofonts/math/actions/runs/8782668417/artifacts/1435159512

### Issue
The weight of the symbol is much lower than other characters

### Screenshot
![image](https://github.com/notofonts/math/assets/2191754/53dfe638-2887-4da7-8cc3-8cf52c78c568)

**Comment by khaledhosny** [comment]
I think it is the other `ssty` glyphs that are too bold, #58.

**Comment by Enivex** [comment]
> I think it is the other `ssty` glyphs that are too bold, #58.

For comparison, here is Fira Math

![image](https://github.com/notofonts/math/assets/2191754/8e372c9f-3f6a-4596-8b8e-afd713c2fb5b)

**Comment by khaledhosny** [comment]
#70:
<img width="466" alt="image" src="https://github.com/notofonts/math/assets/93914/3e996923-7808-43a1-b1e4-a971c8244f92">

**Comment by Enivex** [comment]
Thank you for all the improvements to the font @khaledhosny !

We finally have an actual alternative to Fira Math in settings where a sans serif font is appropriate. 😊

(The only thing I've noticed missing so far is matching chancery, roundhand and fraktur, but I can work around that by changing notation.)
