### ISSUE TITLE
I (capital i) has serifs

### ISSUE THREAD

**Issue by Enivex** [notofonts/math#72]
I (capital i) and l (lowercase L) in Noto Sans Math
![image](https://github.com/notofonts/math/assets/2191754/fcfbaa11-120a-454c-b3eb-1effe56e2750)

for comparison, Fira math
![image](https://github.com/notofonts/math/assets/2191754/bb6c44f2-aa6f-40c4-95f1-d2399eeaf519)

**Comment by apoorvpotnis** [comment]
It seems this is intentional. Otherwise there might be confusion between the lowercase I and the uppercase one. `sansmathfonts` also provides a serif I option.

**Comment by Enivex** [comment]
> It seems this is intentional. Otherwise there might be confusion between the lowercase I and the uppercase one. `sansmathfonts` also provides a serif I option.

That's why I provided a comparison with lowercase L. It's possible to disambiguate in different ways.

Even if Noto Sans Math kept the serifs, it might be worth considering making them less intrusive? They feel a bit out of place to my eyes.

**Comment by khaledhosny** [comment]
This is the same as Noto Sans, so I don’t think it is going to change. There are more than one way to make Il standout in sans-serif fonts, adding serifs to the I is the most reliable way as you can then immediately tell it is an I even if there is no l next to it. If it were up to me, I’d make the l hooked as well, so it also stands out without an I next to it.

**Comment by Enivex** [comment]
> This is the same as Noto Sans, so I don’t think it is going to change. There are more than one way to make Il standout in sans-serif fonts, adding serifs to the I is the most reliable way as you can then immediately tell it is an I even if there is no l next to it. If it were up to me, I’d make the l hooked as well, so it also stands out without an I next to it.

If it's intentional, and matches Noto Sans, then I have no issue with it. I wouldnt mind a hooked l either.

Should I just close this issue?

**Comment by khaledhosny** [comment]
> Should I just close this issue?

Up to you or Simon. The glyph have been there when I worked in the font, so it is just my guess.

**Comment by simoncozens** [comment]
I think we'll keep the existing style.
