### ISSUE TITLE
Overline is very high up

### ISSUE THREAD

**Issue by Enivex** [notofonts/math#75]
Noto Sans Math
![image](https://github.com/notofonts/math/assets/2191754/8d9c86c8-532e-4da9-93d5-30b8118a125d)

Fira Math
![image](https://github.com/notofonts/math/assets/2191754/ca4ab23a-23ac-419e-873d-c18513cf346d)

(Possibly combined with macron being slightly low)

**Comment by khaledhosny** [comment]
I don’t think they are expected to be the same height (overline is “drawn” based on MATH table constants, while the macron is a glyph in the font). I checked Latin Modern Math, STIX Two Math, and Cambria Math and non of them has the overline at the same height as the macron.

**Comment by Enivex** [comment]
I don't necessarily expect them to be at the same height (it was just for illustration purposes). But I did react to the height in some formulas, and felt it was a bit excessive. I'll look into it more closely.

**Comment by khaledhosny** [comment]
We can certainly make the overline a bit lower, but I’d check other fonts and more formulas before making a decision here (we are already using a value lower than what OpenType MATH spec suggests for the overline gab).

**Comment by Enivex** [comment]
<img width="285" alt="comparisonoverline" src="https://github.com/notofonts/math/assets/2191754/172725e2-68c4-4790-91c7-108544f4677e">

New Computer Modern Math -> Stix Two Math -> Noto Sans Math

(Unfortunately the size doesn't match perfectly)

I'd consider NCMM the odd one out here, where it's _very_ low.
