### ISSUE TITLE
OpenType MATH Table in latest release

### ISSUE THREAD

**Issue by JimEBlevins** [notofonts/math#87]
The [documentation](https://github.com/notofonts/math/blob/main/documentation/Noto-Sans-Math-Specimen-v2-539.pdf) suggests that Dr. Hosny has prepared an [OpenType MATH Table](https://learn.microsoft.com/en-us/typography/opentype/spec/math) for Noto Sans Math. 

This contribution merits mention in the release announcement and ReadMe documentation, methinks. 

Thanks for [another](https://tug.org/TUGboat/tb44-2/tb137vieth-otmath.html) great contribution to mathematical typesetting!

**Comment by simoncozens** [comment]
It's not quite true - a MATH table was added early last year by Delve Witherington and Jeff Kellum, but has been reworked and updated recently by Khaled. But all three should go in CONTRIBUTORS, yes.
