### ISSUE TITLE
Numerals have no anchors

### ISSUE THREAD

**Issue by MAZ06** [notofonts/math#92]
### Font 
NotoSansMath-Regular.ttf

### Where the font came from, and when
https://github.com/notofonts/math/releases

### Font Version
Noto Math 3.000

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
Just putting this here in reference to https://github.com/notofonts/latin-greek-cyrillic/issues/487.

Apparently numerals have no anchors and they probably should.

**Comment by khaledhosny** [comment]
The marks should be positioned with the MATH table data (i.e. using MathML or math mode in TeX). Positioning using GPOS anchors is out of scope for Noto Sans Math.
